version: "3.9"
services:
  second:
    image: "my_app_image:latest"
    container_name: "test1"
    ports:
      - "8000:9090"
    volumes:
      - named_vol2:/metindemir
  strongest:
    image: "my_app_image:latest"
    container_name: "test2"
    ports:
      - "5050:9090"
    volumes:
      - named_vol1:/metindemir
volumes:
  named_vol2:
    name: "second_app_volume"
  named_vol1:
    name: "strongest_app_volume"




